In [1]:
import numpy as np
import tensorflow as tf

In [2]:
# as_numpy_iterator(넘파이 배열로 변환)
dataset = tf.data.Dataset.range(10)
dataset_np = dataset.as_numpy_iterator()
print(f"{dataset}, type: {type(dataset)}")
print(f"{dataset_np}, type: {type(dataset_np)}")

<RangeDataset shapes: (), types: tf.int64>, type: <class 'tensorflow.python.data.ops.dataset_ops.RangeDataset'>
<tensorflow.python.data.ops.dataset_ops._NumpyIterator object at 0x7f43c2f4f310>, type: <class 'tensorflow.python.data.ops.dataset_ops._NumpyIterator'>


In [3]:
# apply(5보다 작은수만 리턴)
dataset = tf.data.Dataset.range(10)

def filter_five(x):
    return x.filter(lambda x: x<5)

list(dataset.apply(filter_five).as_numpy_iterator())

[0, 1, 2, 3, 4]

In [4]:
# from_tensor_slices(Dataset 클래스로 변환)
ds = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5])
print(type(ds))
list(ds.as_numpy_iterator())

<class 'tensorflow.python.data.ops.dataset_ops.TensorSliceDataset'>


[1, 2, 3, 4, 5]

In [5]:
# iterattion
ds = tf.data.Dataset.from_tensor_slices([1,2,3,4,5])

for d in ds:
    print(d)
print()

for d in ds.take(3):
    print(d)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [6]:
# range
df = tf.data.Dataset.range(1, 10, 2)

for d in ds:
    print(d)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [7]:
# batch
ds = tf.data.Dataset.range(8)

for d in ds.batch(3):
    print(d)

tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([3 4 5], shape=(3,), dtype=int64)
tf.Tensor([6 7], shape=(2,), dtype=int64)


In [8]:
# dror remainder
ds = tf.data.Dataset.range(8)
for d in ds.batch(3, drop_remainder=True):
    print(d)

tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([3 4 5], shape=(3,), dtype=int64)


In [9]:
# window
ds = tf.data.Dataset.range(10)
ds = ds.window(5, shift=2, drop_remainder=False) # drop_remainder=False
for d in ds:
    print(list(d.as_numpy_iterator()))
print()

ds = tf.data.Dataset.range(10)
ds = ds.window(5,shift=2, drop_remainder=True) # drop_remainder=True(일반적)
for d in ds:
    print(list(d.as_numpy_iterator()))

[0, 1, 2, 3, 4]
[2, 3, 4, 5, 6]
[4, 5, 6, 7, 8]
[6, 7, 8, 9]
[8, 9]

[0, 1, 2, 3, 4]
[2, 3, 4, 5, 6]
[4, 5, 6, 7, 8]


In [10]:
# flat_map
ds = tf.data.Dataset.range(10)
ds = ds.window(5, shift=1, drop_remainder=True) # drop_remainder=False
for d in ds:
    print(d)
print()

ds = tf.data.Dataset.range(10)
ds = ds.window(5, shift=1, drop_remainder=True)
ds = ds.flat_map(lambda w:w.batch(5))
for d in ds:
    print(d)

<_VariantDataset shapes: (), types: tf.int64>
<_VariantDataset shapes: (), types: tf.int64>
<_VariantDataset shapes: (), types: tf.int64>
<_VariantDataset shapes: (), types: tf.int64>
<_VariantDataset shapes: (), types: tf.int64>
<_VariantDataset shapes: (), types: tf.int64>

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)
tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int64)
tf.Tensor([3 4 5 6 7], shape=(5,), dtype=int64)
tf.Tensor([4 5 6 7 8], shape=(5,), dtype=int64)
tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int64)


In [11]:
# shuffle
ds = tf.data.Dataset.from_tensor_slices(np.arange(10))

for d in ds:
    print(d)
print()

ds = tf.data.Dataset.from_tensor_slices(np.arange(10)).shuffle(buffer_size=5)
for d in ds:
    print(d)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)

tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)


In [12]:
# map
window_size=5

ds = tf.data.Dataset.range(10)
ds = ds.window(window_size, shift=1, drop_remainder=True)
ds = ds.flat_map(lambda w: w.batch(window_size))
ds = ds.shuffle(10)

# 첫 4개와 마지막 1개를 분리
ds = ds.map(lambda w:(w[:-1],w[-1]))
for x, y in ds:
    print(f"train set: {x}\nlabel set:{y}")
    print('==='*10)

train set: [4 5 6 7]
label set:8
train set: [0 1 2 3]
label set:4
train set: [2 3 4 5]
label set:6
train set: [5 6 7 8]
label set:9
train set: [1 2 3 4]
label set:5
train set: [3 4 5 6]
label set:7
