## 1.Making Tensor

In [1]:
import torch
import numpy as np

x = torch.empty(5, 4) # 5x4 임의의 텐서 
print(f"tensor:\n{x}, shape:{x.shape}\n")

ones = torch.ones((3,3)) # 3x3 1 텐서
print(f"ones:\n{ones}, shape:{ones.shape}\n")

zeros = torch.zeros(4) # 4개 0 텐서
print(f"zeros:\n{zeros}, shape:{zeros.shape}\n")

rand = torch.rand(5, 6) # 5x6 랜뎀 텐서(표준 정규분포를 기준으로 생성)
print(f"rand:\n{rand}, shape:{rand.shape}")

tensor:
tensor([[2.9308e+11, 3.0694e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]), shape:torch.Size([5, 4])

ones:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]), shape:torch.Size([3, 3])

zeros:
tensor([0., 0., 0., 0.]), shape:torch.Size([4])

rand:
tensor([[0.8167, 0.3491, 0.1979, 0.5861, 0.8890, 0.6517],
        [0.5443, 0.5425, 0.4533, 0.9558, 0.7315, 0.6786],
        [0.9506, 0.4893, 0.4423, 0.8704, 0.4637, 0.2309],
        [0.3516, 0.5124, 0.1805, 0.4228, 0.6833, 0.3925],
        [0.5296, 0.5150, 0.6997, 0.1066, 0.3990, 0.7912]]), shape:torch.Size([5, 6])


## 2.List,ndarray -> Tensor

In [2]:
import torch
import numpy as np

l = [1,3,5] # list
ar = np.array([11,12,13]) # ndarray
print(f"list: {l}")
print(f"ndarray: {ar}\n")

te1 = torch.tensor(l) # list -> tensor
te2 = torch.tensor(ar) # ndarray -> tensor
print(f"list -> tensor: {te1}")
print(f"ndarray -> tensor: {te2}\n")

# tensor -> list
ar1 = np.array(te1) 
ar2 = te2.numpy()
print(f"ar1:\n{ar1}")
print(f"ar2:\n{ar2}")

list: [1, 3, 5]
ndarray: [11 12 13]

list -> tensor: tensor([1, 3, 5])
ndarray -> tensor: tensor([11, 12, 13])

ar1:
[1 3 5]
ar2:
[11 12 13]


## 3.size,type of Tensor

In [3]:
import torch
import numpy as np

x = np.random.randint(0, 10, (3, 4))
tensor = torch.tensor(x)

# size
print(tensor.size())

# type
print(f"type: {type(tensor)}")

torch.Size([3, 4])
type: <class 'torch.Tensor'>


## 4.addition of Tensor

In [4]:
import torch

x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(f"x:\n{x}")
print(f"y:\n{y}\n")

print(f"x + y:\n{x + y}")
print(f"torch.add(x, y):\n{torch.add(x, y)}")
print(f"x.add(y):\n{x.add(y)}\n")

print(f"x.add_(y):\n{x.add_(y)}") # inplace
print(f"x:\n{x}")

x:
tensor([[0.4617, 0.3351],
        [0.1904, 0.2393]])
y:
tensor([[0.4905, 0.9718],
        [0.2111, 0.9473]])

x + y:
tensor([[0.9522, 1.3068],
        [0.4015, 1.1866]])
torch.add(x, y):
tensor([[0.9522, 1.3068],
        [0.4015, 1.1866]])
x.add(y):
tensor([[0.9522, 1.3068],
        [0.4015, 1.1866]])

x.add_(y):
tensor([[0.9522, 1.3068],
        [0.4015, 1.1866]])
x:
tensor([[0.9522, 1.3068],
        [0.4015, 1.1866]])


## 5.Changing size of Tensor

In [5]:
import torch

x = torch.rand((8, 8))
print(f"x.size: {x.size()}\n")

# view
print(f"x.view(64): {x.view(64).size()}")
print(f"x.view(-1, 4, 4): {x.view(-1, 4, 4).size()}")

x.size: torch.Size([8, 8])

x.view(64): torch.Size([64])
x.view(-1, 4, 4): torch.Size([4, 4, 4])


## 6.단일 텐서에서 값으로 뽑아내기

In [6]:
import torch

x = torch.ones(1, dtype=int)

print(f"x: {x}")
print(f"x.item(): {x.item()}")

x: tensor([1])
x.item(): 1
