In [1]:
import torch

# 자동 미분 준비
x = torch.ones((2,2), requires_grad=True) # requires_grad=True: 해당 텐서를 기준으로 모든 연산들을 추적(x를 기준으로 미분 가능)
y = x + 1
z = 2*y**2
result = z.mean()

print(f"x:\n{x}")
print(f"y:\n{y}")
print(f"z:\n{z}")
print('result:\n', result, '\n') # grad_fn=..은 추적이 잘되고 있다는 의미

# Backpropagation
result.backward() # result 기준으로 Backpropagation을 진행
print(f"x.grad:\n{x.grad}") # x.grad: backward()가 선언된 기준으로 미분을 계산(d(result)/dx)

x:
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
y:
tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
z:
tensor([[8., 8.],
        [8., 8.]], grad_fn=<MulBackward0>)
result:
 tensor(8., grad_fn=<MeanBackward0>) 

x.grad:
tensor([[2., 2.],
        [2., 2.]])
